services:

  flow-discord-console-cmds-dev:
    build: .
    container_name: flow-discord-console-cmds-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - flow-console-data-dev:/app/data
    networks:
      - vps-shared
    environment:
      DISCORD_TOKEN:  ${DISCORD_TOKEN}
      CLIENT_ID:      ${CLIENT_ID}
      GUILD_ID:       ${GUILD_ID}
      BOT_WS_PORT:    ${BOT_WS_PORT:-9090}
    profiles: ["dev"]

  flow-discord-console-cmds-prod:
    build: .
    container_name: flow-discord-console-cmds-prod
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - flow-console-data-prod:/app/data
    networks:
      - vps-shared
    environment:
      DISCORD_TOKEN:  ${DISCORD_TOKEN}
      CLIENT_ID:      ${CLIENT_ID}
      GUILD_ID:       ${GUILD_ID}
      BOT_WS_PORT:    ${BOT_WS_PORT:-9090}
    profiles: ["prod"]

volumes:
  flow-console-data-dev:
  flow-console-data-prod:

networks:
  vps-shared:
    external: true
